# Generated by Django 4.2.11 on 2024-09-23 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newspaper',
            name='image_url',
        ),
    ]
