# Generated by Django 4.2.11 on 2024-09-23 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newspapers', '0002_remove_newspaper_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='newspaper',
            name='image_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newspaper',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
