# Generated by Django 4.2.11 on 2024-09-24 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('newspapers', '0003_newspaper_image_url_alter_newspaper_published_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newspaper',
            options={'ordering': ('published_date',)},
        ),
        migrations.AlterModelOptions(
            name='redactor',
            options={'ordering': ('username', 'years_of_experience')},
        ),
        migrations.AlterField(
            model_name='redactor',
            name='groups',
            field=models.ManyToManyField(blank=True, related_name='redactors', related_query_name='redactor', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='redactor',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, related_name='redactors', related_query_name='redactor', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
